# Generated by Django 5.1.6 on 2026-02-21 03:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('num_cards', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('arcana', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor')], max_length=10)),
                ('suit', models.CharField(blank=True, choices=[('wands', 'Wands'), ('cups', 'Cups'), ('swords', 'Swords'), ('pentacles', 'Pentacles')], max_length=20, null=True)),
                ('keywords_upright', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('keywords_reversed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('meaning_upright', models.TextField()),
                ('meaning_reversed', models.TextField()),
                ('image_filename', models.CharField(blank=True, max_length=200)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tarot.deck')),
            ],
            options={
                'ordering': ['arcana', 'suit', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarot.deck')),
                ('spread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarot.spread')),
            ],
        ),
        migrations.CreateModel(
            name='SpreadPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thematic_note', models.TextField(blank=True)),
                ('spread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='tarot.spread')),
            ],
            options={
                'ordering': ['position_number'],
                'unique_together': {('spread', 'position_number')},
            },
        ),
        migrations.CreateModel(
            name='ReadingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reversed', models.BooleanField(default=False)),
                ('interpretation', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarot.card')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tarot.reading')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarot.spreadposition')),
            ],
            options={
                'unique_together': {('reading', 'position')},
            },
        ),
    ]
